### ISSUE TITLE
issue with twiml update

### ISSUE THREAD

**Issue by freegenie** [bruno222/twilio-flex-plugin-forward-to-ivr#3]
Hi, I've been trying this solution but we get an error during the update a this line: 

https://github.com/bruno222/twilio-flex-plugin-transfer-to-ivr/blob/783c1792f84ae97b5c629b7cea2b15da88de0e72/.docs/function-send-to-flex-and-back-to-studio.js#L59

**Comment by bruno222** [comment]
Hi @freegenie , I am leaving for vacation. Could you please open a support ticket with our team?

They will ask which error are you getting, so please send it in advance.

Thanks cheers.
